"""enhance payment processing

Revision ID: 76fdc6c41a8a
Revises: e337f96d6cd5
Create Date: 2026-09-27 15:31:59.239599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fdc6c41a8a'
down_revision: Union[str, Sequence[str], None] = 'e337f96d6cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('payments', sa.Column('three_ds_required', sa.Boolean(), nullable=False))
    op.add_column('payments', sa.Column('three_ds_status', sa.String(length=30), nullable=False))
    op.add_column('payments', sa.Column('authorization_status', sa.String(length=30), nullable=False))
    op.add_column('payments', sa.Column('provider_reference', sa.String(length=80), nullable=True))
    op.add_column('payments', sa.Column('failure_code', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('failure_reason', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'retry_count')
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'failure_code')
    op.drop_column('payments', 'provider_reference')
    op.drop_column('payments', 'authorization_status')
    op.drop_column('payments', 'three_ds_status')
    op.drop_column('payments', 'three_ds_required')
    op.drop_column('payments', 'currency')
    # ### end Alembic commands ###
